#This solution, non-production-ready template describes AWS Codepipeline based CICD Pipeline for terraform code deployment.
#© 2023 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
#This AWS Content is provided subject to the terms of the AWS Customer Agreement available at
#http://aws.amazon.com/agreement or other written agreement between Customer and either
#Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.4.6"
    TF_MODULE_TO_BUILD: "network"
    ENVIRONMENT: "demo"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"
  build:
    commands:
      - "echo ## TERRAFORM APPLY : Starting with the Terraform Apply"
      - "/bin/bash ${CODEBUILD_SRC_DIR}/run.sh -m ${TF_MODULE_TO_BUILD} -env ${ENVIRONMENT} -region ${AWS_REGION} -tfcmd apply"
artifacts:
  files:
    - '**/*'